services:
  api-gateway:
    # Remplace le build local par l'image pré-buildée depuis GitHub Packages
    image: ghcr.io/rundredoffi/api-gateway:latest
    # Supprime la directive build: ./api-gateway
    ports:
      - "8888:8888"
    networks:
      - gateway_net
    depends_on:
      - ms-user
      - ms-locations
      - kafka
    restart: unless-stopped
    # Monte la configuration externalisée
    volumes:
      - ./config/api-gateway.yml:/app/config/application.yml:ro

  ms-user:
    # Remplace le build local par l'image pré-buildée depuis GitHub Packages
    image: ghcr.io/rundredoffi/msuser:latest
    # Supprime la directive build: ./msuser
    expose:
      - "8080"
    environment:
      - DATABASE_HOST=user-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=msuser_db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
    networks:
      - gateway_net
      - user_net
    depends_on:
      user-db:
        condition: service_healthy
    restart: unless-stopped
    # Monte la configuration externalisée
    volumes:
      - ./config/msuser.yml:/app/config/application.yml:ro

  ms-locations:
    # Remplace le build local par l'image pré-buildée depuis GitHub Packages
    image: ghcr.io/rundredoffi/ms-locations:latest
    expose:
      - "8081"
    environment:
      - DATABASE_HOST=location-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=mslocations_db
      - DATABASE_USER=location_user
      - DATABASE_PASSWORD=location_pass
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - gateway_net
      - location_net
    depends_on:
      location-db:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./config/mslocations.yml:/app/config/application.yml:ro