# MS-Locations Configuration
spring:
  application:
    name: ms-locations

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:mslocations_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DATABASE_USER:location_user}
    password: ${DATABASE_PASSWORD:location_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8081

# Logs
logging:
  level:
    com.micros.mslocations: DEBUG
    org.springframework.kafka: INFO